# Generated by Django 3.1.4 on 2021-02-05 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appLabour', '0004_auto_20210205_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='Age',
            field=models.IntegerField(),
        ),
    ]
