# Generated by Django 3.1.4 on 2021-02-05 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appLabour', '0005_auto_20210205_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='Photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
