# Generated by Django 3.1.4 on 2021-02-05 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appLabour', '0007_auto_20210205_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='Photo',
        ),
    ]
