# Generated by Django 3.1.4 on 2021-02-05 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appLabour', '0008_remove_sample_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='Photo',
            field=models.ImageField(default=0, upload_to='media/'),
        ),
    ]
