# Generated by Django 3.1.4 on 2021-02-05 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appLabour', '0010_auto_20210205_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='Photo',
            field=models.ImageField(default=0, upload_to='media/'),
        ),
    ]
