# Generated by Django 3.1.4 on 2021-02-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appLabour', '0013_auto_20210205_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='Photo',
            field=models.ImageField(upload_to='', verbose_name='media'),
        ),
    ]
