# Generated by Django 3.1.6 on 2021-02-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appLabour', '0014_auto_20210205_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='Photo',
            field=models.ImageField(default=0, upload_to='media/'),
        ),
    ]
