# Generated by Django 3.1.6 on 2021-02-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appLabour', '0016_auto_20210205_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='Photo',
            field=models.ImageField(default=0, upload_to='media/'),
        ),
    ]
