# Generated by Django 3.1.6 on 2021-02-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appLabour', '0019_auto_20210207_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='EducationalQualifications',
            field=models.CharField(choices=[('SSLC', 'SSLC'), ('PLUSTWO', 'PLUSTWO'), ('DEGREE', 'DEGREE'), ('BETCH', 'BETCH'), ('OTHERS', 'OTHERS')], max_length=100),
        ),
        migrations.AlterField(
            model_name='sample',
            name='LanguageKnown',
            field=models.CharField(choices=[('ENGLISH', 'ENGLISH'), ('HINDI', 'HINDI'), ('MALAYALAM', 'MALAYALAM')], max_length=100),
        ),
    ]
