# Generated by Django 3.1.6 on 2021-02-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appLabour', '0020_auto_20210207_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='EducationalQualifications',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='sample',
            name='LanguageKnown',
            field=models.CharField(default='', max_length=100),
        ),
    ]
