# Generated by Django 3.1.6 on 2021-02-07 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appLabour', '0021_auto_20210207_2212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='LanguageKnown',
            new_name='LanaguageKnown',
        ),
    ]
