# Generated by Django 3.1.6 on 2021-02-07 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appLabour', '0022_auto_20210207_2238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='EducationalQualifications',
            new_name='EducationalQualification',
        ),
    ]
