# Generated by Django 3.1.6 on 2021-02-08 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appLabour', '0023_auto_20210207_2316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='LanaguageKnown',
            new_name='LanguageKnown',
        ),
    ]
