# Generated by Django 3.1.6 on 2021-02-08 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appLabour', '0024_auto_20210208_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='Status',
            field=models.BooleanField(default=False),
        ),
    ]
