# Generated by Django 3.1.6 on 2021-02-08 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appLabour', '0025_sample_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='Status',
        ),
    ]
