# Generated by Django 3.1.6 on 2021-02-17 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appLabour', '0028_sample_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Color', models.CharField(max_length=100)),
                ('Price', models.CharField(max_length=100)),
                ('Image1', models.ImageField(default=0, upload_to='media/')),
                ('Image2', models.ImageField(default=0, upload_to='media/')),
                ('Image3', models.ImageField(default=0, upload_to='media/')),
            ],
        ),
    ]
