# Generated by Django 3.1.6 on 2021-02-19 06:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appLabour', '0031_auto_20210217_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='PhoneNumber',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="PhoneNumber must be entered in the format:'+999999999'. up to 15 digits allowed.", regex='^\\+?1\\d{9,15}$')]),
        ),
    ]
