# Generated by Django 3.1.6 on 2021-02-26 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appLabour', '0033_auto_20210226_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
    ]
